import { Inter } from "next/font/google";
import "../css/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggleButton } from "@/components/ThemeToggleButton";
import { Toaster } from 'sonner';
import { ShieldAlert } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "My Job Portal App",
    description: "Generated by me",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                    <ThemeToggleButton></ThemeToggleButton>
                    <Toaster richColors closeButton icons={{
                        error: <ShieldAlert />
                    }} />
                </ThemeProvider>

            </body>
        </html>
    );
}
